import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { decodeAuditDetail } from "./request-audits-api.ts";

// Generated by TestAuditGenerationDetailContract through the actual HTTP handler.
function fixture() {
  return JSON.parse(readFileSync(join(import.meta.dirname, "__fixtures__", "generation-detail.json"), "utf8")).data;
}

test("audit detail preserves each generation without combining main usage", () => {
  const value = decodeAuditDetail(fixture());
  assert.equal(value.audit.inputTokens, 20);
  assert.equal(value.audit.costInUsdTicks, 55);
  assert.equal(value.generationUsages?.length, 2);
  const [first, selected] = value.generationUsages!;
  assert.equal(first.selected, false);
  assert.equal(first.inputTokens, 100);
  assert.equal(first.cachedInputTokens, 30);
  assert.equal(first.cacheCreationTokens, 2);
  assert.equal(first.contextInputTokens, 120);
  assert.equal(selected.selected, true);
  assert.equal(selected.accountId, "36028797018963969");
});

test("older server responses may omit generation details without guessing", () => {
  const value = fixture();
  delete value.generationUsages;
  assert.equal(decodeAuditDetail(value).generationUsages, undefined);
  value.generationUsages = [];
  assert.deepEqual(decodeAuditDetail(value).generationUsages, []);
});

test("present generation details require numeric counters and explicit outcome/source", () => {
  for (const [key, invalid] of [["inputTokens", "20"], ["outcome", "success"], ["usageSource", "calculated"], ["accountId", 123]]) {
    const value = fixture();
    value.generationUsages[0][key as string] = invalid;
    assert.throws(() => decodeAuditDetail(value));
  }
});
