import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { decodeAuditDetail } from "@/entities/audit/audit-api.ts";

// Generated by TestAuditGenerationDetailContract through the actual HTTP handler.
function fixture() {
  return JSON.parse(readFileSync(join(import.meta.dirname, "__fixtures__", "generation-detail.json"), "utf8")).data;
}

test("audit detail preserves each generation without combining main usage", () => {
  const value = decodeAuditDetail(fixture());
  assert.equal(value.audit.inputTokens, 20);
  assert.equal(value.audit.costInUsdTicks, 55);
  assert.equal(value.generationUsages?.length, 2);
  const [first, selected] = value.generationUsages!;
  assert.equal(first.selected, false);
  assert.equal(first.inputTokens, 100);
  assert.equal(first.cachedInputTokens, 30);
  assert.equal(first.cacheCreationTokens, 2);
  assert.equal(first.contextInputTokens, 120);
  assert.equal(selected.selected, true);
  assert.equal(selected.accountId, "36028797018963969");
});

test("older server responses may omit generation details without guessing", () => {
  const value = fixture();
  delete value.generationUsages;
  assert.equal(decodeAuditDetail(value).generationUsages, undefined);
  value.generationUsages = [];
  assert.deepEqual(decodeAuditDetail(value).generationUsages, []);
});

test("cache presence preserves false, zero and missing fields from old servers", () => {
  for (const reported of [true, false, undefined]) {
    const value = fixture();
    value.audit.cachedInputTokens = 0;
    value.audit.cachedInputTokensReported = reported;
    value.generationUsages[0].cachedInputTokens = 0;
    value.generationUsages[0].cachedInputTokensReported = reported;
    const decoded = decodeAuditDetail(value);
    assert.equal(decoded.audit.cachedInputTokensReported, reported);
    assert.equal(decoded.generationUsages?.[0].cachedInputTokensReported, reported);
  }
  const invalid = fixture();
  invalid.audit.cachedInputTokensReported = "false";
  assert.throws(() => decodeAuditDetail(invalid));
});

test("present generation details require numeric counters and explicit outcome/source", () => {
  for (const [key, invalid] of [["inputTokens", "20"], ["outcome", "success"], ["usageSource", "calculated"], ["accountId", 123]]) {
    const value = fixture();
    value.generationUsages[0][key as string] = invalid;
    assert.throws(() => decodeAuditDetail(value));
  }
});

test("execution diagnostics preserve connection reuse and string identities while old rows remain unknown", () => {
  const value = fixture();
  assert.equal(decodeAuditDetail(value).audit.diagnostics, undefined);
  value.audit.diagnostics = {
    version: 1,
    stages: [{ stage: "history_commit", us: 1750, calls: 1 }],
    failures: [{ component: "history", stage: "store", reason: "store_lock" }],
    exchanges: [{ physicalId: "synthetic/1", accountId: "36028797018963969", nodeId: "3", epoch: "1", plane: "build", stage: "primary", status: 200, us: 2000,
      events: [{ stage: "got_conn", us: 100, reused: true }] }],
  };
  const decoded = decodeAuditDetail(value).audit.diagnostics!;
  assert.equal(decoded.exchanges?.[0].events?.[0].reused, true);
  assert.equal(decoded.exchanges?.[0].accountId, "36028797018963969");
  value.audit.diagnostics.exchanges[0].accountId = 123;
  assert.throws(() => decodeAuditDetail(value));
});
