// Package attemptmeta carries immutable request and physical attempt identity.
// It never puts metadata into upstream headers or reconstructs paths on receipt.
package attemptmeta

import (
	"context"
	"net/http"
	"strconv"
	"sync/atomic"
	"time"
)

type PathStatus string

const (
	PathUnknown    PathStatus = "unknown"
	PathRegistered PathStatus = "registered"
	PathVerified   PathStatus = "verified"
	PathDirect     PathStatus = "direct"
)

type Path struct {
	NodeID   uint64     `json:"node_id,omitempty"`
	Epoch    uint64     `json:"epoch,omitempty"`
	Status   PathStatus `json:"status"`
	Rotating bool       `json:"rotating,omitempty"`
}

// Identity is a value, fixed before a physical HTTP request is submitted.
// RequestID is generated by the gateway and contains no caller-provided text.
type Identity struct {
	Profile     Profile   `json:"profile"`
	ID          string    `json:"id"`
	RequestID   string    `json:"request_id"`
	Ordinal     uint64    `json:"ordinal"`
	AccountID   uint64    `json:"account_id"`
	Provider    string    `json:"provider"`
	Model       string    `json:"model"`
	Revision    uint64    `json:"revision"`
	RuleVersion string    `json:"rule_version"`
	StartedAt   time.Time `json:"started_at"`
	Path        Path      `json:"path"`
}

// Profile describes the normalized generation payload, without retaining user
// content. Experiment labels are set by the internal probe executor only.
type Profile struct {
	Known           bool   `json:"known"`
	Protocol        string `json:"protocol,omitempty"`
	ReasoningEffort string `json:"reasoning_effort,omitempty"`
	Tools           bool   `json:"tools"`
	Experiment      string `json:"experiment,omitempty"`
	Sample          string `json:"sample,omitempty"`
}

// PathResolver returns the registered path version at the time of submission.
// Registration alone does not verify the exit actually used by a rotating proxy.
type PathResolver interface {
	PathVersion(nodeID uint64) (epoch uint64, known bool)
}
type scope struct {
	base     Identity
	ordinal  *atomic.Uint64
	resolver PathResolver
}
type scopeKey struct{}
type identityKey struct{}

func WithRequest(ctx context.Context, requestID string, revision uint64, ruleVersion string, resolver PathResolver) context.Context {
	return context.WithValue(ctx, scopeKey{}, scope{base: Identity{RequestID: requestID, Revision: revision, RuleVersion: ruleVersion}, ordinal: &atomic.Uint64{}, resolver: resolver})
}

func WithAccount(ctx context.Context, accountID uint64, provider, model string) context.Context {
	s, ok := ctx.Value(scopeKey{}).(scope)
	if !ok {
		return ctx
	}
	s.base.AccountID, s.base.Provider, s.base.Model = accountID, provider, model
	return context.WithValue(ctx, scopeKey{}, s)
}

func WithProfile(ctx context.Context, profile Profile) context.Context {
	s, ok := ctx.Value(scopeKey{}).(scope)
	if !ok {
		return ctx
	}
	s.base.Profile = profile
	return context.WithValue(ctx, scopeKey{}, s)
}

// WithNormalizedProfile preserves server-owned experiment labels while replacing
// claimed request settings with the actual settings submitted to the provider.
func WithNormalizedProfile(ctx context.Context, protocol, effort string, tools, known bool) context.Context {
	s, ok := ctx.Value(scopeKey{}).(scope)
	if !ok {
		return ctx
	}
	s.base.Profile.Protocol, s.base.Profile.ReasoningEffort = protocol, effort
	s.base.Profile.Tools, s.base.Profile.Known = tools, known
	return context.WithValue(ctx, scopeKey{}, s)
}

// Begin creates a new physical identity. Retries and auxiliary calls get their
// own ordinal even when they share an account, HTTP client or request context.
func Begin(ctx context.Context, path Path) context.Context {
	s, ok := ctx.Value(scopeKey{}).(scope)
	if !ok {
		return ctx
	}
	id := s.base
	id.Ordinal = s.ordinal.Add(1)
	id.ID = id.RequestID + "/" + strconv.FormatUint(id.Ordinal, 10)
	id.StartedAt = time.Now().UTC()
	if path.Status == "" {
		path.Status = PathUnknown
	}
	if path.NodeID != 0 && s.resolver != nil {
		if epoch, known := s.resolver.PathVersion(path.NodeID); known {
			path.Epoch = epoch
			if !path.Rotating {
				path.Status = PathRegistered
			}
		}
	}
	id.Path = path
	return context.WithValue(ctx, identityKey{}, id)
}

func FromContext(ctx context.Context) Identity {
	if ctx == nil {
		return Identity{}
	}
	id, _ := ctx.Value(identityKey{}).(Identity)
	return id
}

func FromResponse(response *http.Response) Identity {
	if response == nil || response.Request == nil {
		return Identity{}
	}
	return FromContext(response.Request.Context())
}

// Attach preserves metadata even for transports that don't return Request.
// A fresh request value prevents another call from changing a saved response.
func Attach(response *http.Response, request *http.Request) {
	if response == nil || request == nil {
		return
	}
	if response.Request == nil {
		response.Request = request.Clone(request.Context())
		return
	}
	response.Request = response.Request.WithContext(request.Context())
}
