export const caseReportZh = {
 changeAccount: "保持出口，更换账号", changeExit: "保持账号，更换出口",
 eyebrow: "本次调查结论", overview: "资源状态", process: "检测经过", processHelp: "固定一个条件，更换另一个条件，逐步排查异常来自哪里。",
 basis: "判定依据", basisHelp: "下面的对照解释了异常为什么归属于这个资源。", record: "检测记录", targetAccount: "涉案账号", targetExit: "涉案出口", controlAccount: "对照账号", controlExit: "对照出口",
 account: "账号", exit: "出口", nameUnavailable: "名称不可用", completed: "检测完成", pending: "等待检测", calls: "检测尝试", generations: "生成请求", duration: "调查耗时", model: "检测模型", seconds: "秒", minutes: "分", attempt: "次", max: "最多", dash: "—",
 flow: "经由", step: "检测", evidence: "依据检测", noEvidence: "尚未取得足够的有效对照。", fetching: "正在读取检测记录…", retry: "重试", loadError: "检测记录读取失败，已有结论仍可查看。", waiting: "正在安排对照检测，结果会自动更新。", empty: "本案尚无可展示的检测记录。",
 history: "结论对应当时的检测；要了解资源当前状态，可在账号或代理页重新进行风控检测。",
 heldNote: "以下处置仅属于本案，其他案件的限制仍可能生效。", normalNote: "响应正常且出现有效思考。", badNote: "响应完整，但没有出现有效思考；需要结合其他检测判断原因。", unknownNote: "未取得完整、可核实的响应，不用于认定资源异常。", conflictNote: "检测信号相互冲突，不能据此归因。", pendingNote: "正在等待这次检测完成。",
 findings: { account: "已确认账号异常", exit: "已确认出口异常", both: "账号和出口均异常", normal: "本次检测正常", inconclusive: "证据不足，暂无法归因", investigating: "正在排查异常来源", reviewed: "本案已人工解除限制" },
 summaries: { account: "对照检测将异常定位到账号，具体依据见下方。", exit: "对照检测将异常定位到出口，具体依据见下方。", both: "账号与出口分别取得异常证据，需要分别处理。", normal: "本次已取得正常响应，涉案资源未复现降智。", inconclusive: "现有结果不足以确定异常来自账号还是出口。", investigating: "系统正在进行对照检测，结论尚未形成。", reviewed: "原检测结果保留供复盘，当前处置以人工复核为准。" },
 outcomes: { healthy: "检测正常", degraded: "确认异常", inconclusive: "无法判定", pending: "待确认" },
 observations: { A: "思考正常", B: "缺少思考", unknown: "检测无效", conflict: "信号冲突", pending: "检测中" },
 dispositions: { remanded: "暂时限制 · 等待调查", sentenced: "已限制使用", released: "本案已释放", withdrawn: "已撤下本案调查", dismissed: "本案已解除", unknown: "处置待确认" },
 reasons: { normal: "完整响应中出现了有效思考，支持该资源在本次检测中正常。", account: "使用同一实际出口时，涉案账号缺少思考，而对照账号思考正常。因此异常跟随账号。", exit: "同一个账号在涉案出口缺少思考，换到另一实际出口后思考正常。因此异常跟随出口。", conflict: "观测相互矛盾，无法形成一致结论；不能按异常次数决定归因。", changed: "检测证据已过期，或账号、出口发生变化，不能用于当前归因。", inconclusive: "尚未取得足够的有效正常对照，无法确定该资源是否异常。" },
 checks: { complete: "响应完整", incomplete: "响应未完整结束", path: "出口已核实", unverified: "出口未核实" },
 stepPurpose: { measure_target: "检查目标组合", resolve_negative: "更换条件作对照", establish_control: "寻找正常对照" },
};
export const caseReportEn = {
 changeAccount: "Same exit, different account", changeExit: "Same account, different exit",
 eyebrow: "Investigation finding", overview: "Resource status", process: "What was checked", processHelp: "Keep one condition fixed and change the other to locate the source.",
 basis: "Why this conclusion", basisHelp: "These comparisons explain the finding for each resource.", record: "Check records", targetAccount: "Target account", targetExit: "Incident exit", controlAccount: "Comparison account", controlExit: "Comparison exit",
 account: "Account", exit: "Exit", nameUnavailable: "Name unavailable", completed: "Completed", pending: "Waiting", calls: "Check attempts", generations: "Generation requests", duration: "Investigation time", model: "Model", seconds: "s", minutes: "m", attempt: "", max: "Up to", dash: "—",
 flow: "via", step: "Check", evidence: "Based on checks", noEvidence: "No sufficient valid comparison yet.", fetching: "Loading check records…", retry: "Retry", loadError: "Check records could not be loaded. The recorded finding is still available.", waiting: "Comparison checks are being arranged. Results update automatically.", empty: "No check records are available for this case.",
 history: "Findings describe the time of testing. Run a risk check from Accounts or Proxies to check the resource again.", heldNote: "These actions belong to this case. Other cases may still restrict the resource.", normalNote: "The response completed with valid visible thinking.", badNote: "The response completed without valid visible thinking. Comparisons are needed to identify the cause.", unknownNote: "No complete, verified response was obtained. This cannot establish a resource anomaly.", conflictNote: "Conflicting signals prevent attribution.", pendingNote: "Waiting for this check to finish.",
 findings: { account: "Account anomaly confirmed", exit: "Exit anomaly confirmed", both: "Both account and exit are abnormal", normal: "Resources passed this check", inconclusive: "Not enough evidence to attribute", investigating: "Investigating the source", reviewed: "Restrictions manually released" },
 summaries: { account: "Comparisons locate the anomaly in the account. See the evidence below.", exit: "Comparisons locate the anomaly in the exit. See the evidence below.", both: "Separate comparisons establish an anomaly in each resource.", normal: "Valid normal responses were obtained; degradation was not reproduced.", inconclusive: "The results do not establish whether the account or exit caused the anomaly.", investigating: "Comparison checks are in progress. A final finding is not yet available.", reviewed: "Original findings remain available; the manual review determines this case's current action." },
 outcomes: { healthy: "Normal in this check", degraded: "Anomaly confirmed", inconclusive: "Inconclusive", pending: "Not yet determined" },
 observations: { A: "Thinking present", B: "Thinking absent", unknown: "Invalid check", conflict: "Conflicting signals", pending: "Checking" },
 dispositions: { remanded: "Temporarily restricted", sentenced: "Use restricted", released: "Released by this case", withdrawn: "Withdrawn from this case", dismissed: "Restriction removed", unknown: "Action unavailable" },
 reasons: { normal: "The completed response contained valid thinking, supporting a normal finding for this check.", account: "On the same actual exit, the target account lacked thinking while a comparison account showed thinking. The anomaly follows the account.", exit: "The same account lacked thinking on the incident exit and showed thinking on another actual exit. The anomaly follows the exit.", conflict: "Observations contradict each other. Counting anomalies cannot resolve the contradiction.", changed: "Evidence expired or the account or exit changed. These observations cannot establish a current finding.", inconclusive: "There are not enough valid normal comparisons to determine this resource's condition." },
 checks: { complete: "Response complete", incomplete: "Response incomplete", path: "Exit verified", unverified: "Exit unverified" },
 stepPurpose: { measure_target: "Check the target pair", resolve_negative: "Change a condition to compare", establish_control: "Find a normal comparison" },
};
