export const resourceCheckZh = {
  resources: "所选资源", resourceHelp: "按各资源最近一次检测显示，选择后查看详情。", search: "搜索所选资源", noMatch: "没有匹配的资源", overview: "检测概览", latest: "最近一次", history: "检测记录", older: "正在查看历史记录", backToLatest: "返回最近一次", result: "本次检测结论", historicalNormal: "检测时正常", account: "账号", node: "出口", target: "检测对象", via: "经由", duration: "检测耗时", model: "检测模型", seconds: "秒", minutes: "分", batchCalls: "本批次检测尝试", batchGenerations: "本批次生成请求", times: "次", batchNote: "次数属于这份报告所在批次，包含共享对照；切换资源不会重复计费。", process: "检测经过", relevant: "当前资源相关检测", all: "查看本批次全部检测", showRelevant: "只看当前资源", basis: "为什么得到这个结论", evidence: "查看依据", step: "检测", targetStep: "检查目标组合", comparisonStep: "补充对照检测", changeAccount: "保持出口，更换账号", changeExit: "保持账号，更换出口", waiting: "检测进度会自动更新，关闭窗口后任务继续执行。", noEvidence: "暂无检测记录可展示。", emptyTitle: "尚未检测这个资源", emptyNote: "选择检测模型并开始，完成后可在这里查看结论和对照过程。", nameError: "部分资源名称暂时无法读取，已用编号显示。", retry: "重试", partial: "部分资源未提交成功", allRunning: "所选资源正在检测", submitNote: "检测消耗上游额度，取得充分证据即停止。批量检测共享对照。", actionNote: "结论对应所选模型与检测时间；检测不会自动禁用资源或解除案件限制。", limit: "每次最多检测 32 个资源，请减少选择后重试。", complete: "响应完整", incomplete: "响应未完整结束", path: "出口已核实", unverified: "出口未核实", flowNote: "保持一个条件不变，通过对照定位异常来源。", unknownNote: "本次未取得可用于归因的有效响应，不能当作资源异常。", normalNote: "响应完整且出现有效思考。", badNote: "响应完整，但缺少有效思考；单次结果不能确定是账号还是出口的问题。", conflictNote: "检测信号冲突，不能据此归因。", pendingNote: "等待本次检测完成。", stoppedNote: "检测未完成，保留已取得的记录，不将中途结果作为最终结论。",
  outcomes: { healthy: "本次检测正常", degraded: "已确认异常", inconclusive: "暂无法判定", pending: "排队中", running: "检测中", failed: "检测未完成", cancelled: "检测已取消", empty: "尚未检测" },
  observations: { A: "思考正常", B: "缺少思考", unknown: "检测无效", conflict: "信号冲突", pending: "检测中" },
  totals: { healthy: "检测正常", degraded: "确认异常", inconclusive: "待确认", running: "进行中", empty: "未检测" },
};
export const resourceCheckEn: typeof resourceCheckZh = {
  resources: "Selected resources", resourceHelp: "Latest check for each resource. Select one to see its report.", search: "Search selected resources", noMatch: "No matching resources", overview: "Check overview", latest: "Latest", history: "Check history", older: "Viewing an earlier check", backToLatest: "Back to latest", result: "Finding for this check", historicalNormal: "Normal when tested", account: "Account", node: "Exit", target: "Selected resource", via: "via", duration: "Check duration", model: "Model", seconds: "s", minutes: "m", batchCalls: "Batch check attempts", batchGenerations: "Batch generation requests", times: "", batchNote: "Counts cover this report's batch, including shared comparisons. Switching resources does not make new requests.", process: "What was checked", relevant: "Checks related to this resource", all: "View all checks in this batch", showRelevant: "Show this resource only", basis: "Why this conclusion", evidence: "View evidence", step: "Check", targetStep: "Check the target combination", comparisonStep: "Run a comparison", changeAccount: "Same exit, different account", changeExit: "Same account, different exit", waiting: "Progress updates automatically. Accepted checks continue after closing this window.", noEvidence: "No check records to display yet.", emptyTitle: "This resource has not been checked", emptyNote: "Select a model and start a check to see the finding and comparisons here.", nameError: "Some resource names could not be loaded. Their IDs are shown instead.", retry: "Retry", partial: "Some resources could not be submitted", allRunning: "Selected resources are being checked", submitNote: "Checks use upstream quota and stop when there is enough evidence. Batch checks share comparisons.", actionNote: "Findings apply to the selected model and test time. Checks do not disable resources or release case restrictions.", limit: "Select at most 32 resources per check.", complete: "Response complete", incomplete: "Response incomplete", path: "Exit verified", unverified: "Exit unverified", flowNote: "Keep one condition fixed and compare the other to locate the cause.", unknownNote: "No valid response was obtained for attribution. This cannot establish an anomaly.", normalNote: "The response completed with valid visible thinking.", badNote: "The response completed without valid thinking. This alone cannot tell whether the account or exit is responsible.", conflictNote: "Conflicting signals prevent attribution.", pendingNote: "Waiting for this check to finish.", stoppedNote: "This check did not finish. Collected records are retained without treating provisional findings as final.",
  outcomes: { healthy: "Normal in this check", degraded: "Anomaly confirmed", inconclusive: "Inconclusive", pending: "Queued", running: "Checking", failed: "Check incomplete", cancelled: "Check cancelled", empty: "Not checked" },
  observations: { A: "Thinking present", B: "Thinking absent", unknown: "Invalid check", conflict: "Conflicting signals", pending: "Checking" },
  totals: { healthy: "Normal", degraded: "Abnormal", inconclusive: "Unresolved", running: "In progress", empty: "Not checked" },
};
